### ISSUE TITLE
no regression tests

### ISSUE THREAD

**Issue by richardjgowers** [ryokbys/nap#2]
The package doesn't have any regression tests currently.  So while I can run an example simualtion, I've got no way of knowing if the numbers produced match what "should" happen.  Ideally there should be a "make test" target which runs the example and checks that the answers are similar/equal to a known set of reference values (which have been checked to be true).

**Comment by ryokbys** [comment]
Thanks for the suggestion. I wrote "Tests" section in the [documentation](http://ryokbys.web.nitech.ac.jp/contents/nap_docs/install.html#tests) about the tests of main programs. I agree to your suggestion about making a "make test" target, and I will be doing it soon.
