### ISSUE TITLE
Build instructions for pmd and fitpot do not work

### ISSUE THREAD

**Issue by foeroyingur** [ryokbys/nap#3]
Following the [build documentation](http://ryokbys.web.nitech.ac.jp/contents/nap_docs/install.html#build-pmd-and-fitpot), i.e.,

> $ ./configure --prefix=$(pwd)
> $ make pmd fitpot

leads to

> make: 'pmd' is up to date.
> make: 'fitpot' is up to date.

**Comment by ryokbys** [comment]
Thanks for your report. 
The bug was fixed at v0.10.2.
