### ISSUE TITLE
Test for parallel execution

### ISSUE THREAD

**Issue by foeroyingur** [ryokbys/nap#4]
Is there a test for parallel execution of pmd? I tried to modify example/pmd_BVS_LLZO to be able to run it using MPI (changed num_nodes_x, num_nodes_y, and num_nodes_z to -1). However, it produces different results depending on the number of MPI processes and I'm not able to judge whether the differences are ok.

**Comment by ryokbys** [comment]
The pmd gives velocities on atoms when initial_temperature is given in `in.pmd` file and the atom velocities could be different when the pmd is executed in different parallel configuration. By removing initial_temperature entry or giving negative value to it, the pmd reads atomic velocities from `pmdini` file, which should result in the identical final potential and kinetic energies even in different parallel configurations. 
I added an example `pmd_paralllel` that tests running pmd in different parallel configurations. Please try v0.10.2 or newer than rev210109.
